FROM node:20.14-alpine
WORKDIR /application
EXPOSE 3000

COPY ./package.json .
COPY ./yarn.lock .
COPY ./secret-key .
RUN apk add --no-cache sqlite libc6-compat
RUN yarn install

ENV NODE_OPTIONS="--unhandled-rejections=strict"

CMD ["node", "."]