FROM node:24
WORKDIR /application
EXPOSE 3000

COPY ./package.json .
COPY ./yarn.lock .
COPY ./secret-key .

RUN apt-get update && apt-get install -y sqlite3 curl tzdata git python3
RUN yarn install --frozen-lockfile --production

ENV NODE_OPTIONS="--unhandled-rejections=strict"
ENV TZ=Europe/Budapest

CMD ["node", "."]