version: '2.4'
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - MONGO_USER=unifi
      - MONGO_PASS=UNIFI_PASSWORD
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=4096
      - MEM_STARTUP=1024
    mem_limit: 4096m
    cpus: 2
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    depends_on:
      - unifi-db
    networks:
      unifi-bridge:
        ipv4_address: 172.18.0.2
    restart: always
    healthcheck:
      test: curl --max-time 10 -kILs --fail https://localhost:8443 || exit 1
      interval: 30s
      timeout: 20s
      retries: 5

  unifi-db:
    image: mongo:4.4
    expose:
      - 27017
    volumes:
      - ./mongodb:/data/db
      - ./initmongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      unifi-bridge:
        ipv4_address: 172.18.0.1
    mem_limit: 4096m
    cpus: 2
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/unifi --quiet
      interval: 15s
      timeout: 15s
      retries: 5

networks:
  unifi-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.254